# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"

  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    # 1000 megabytes -> 1 gigabyte
    v.memory = 1000
  end

  # Server 1
  config.vm.define "sandbox" do |s1|
    s1.vm.hostname = "sandbox"
    s1.vm.network :private_network, ip: "192.168.69.8"
  end

  # run ansible playbook
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yml"
  end


end
