---
- name: Example 01
  hosts: all
  become: yes
  tasks:
    - name: Install vim
      apt:
        name:
        - vim
        - tree
        state: latest

#  install_dev_tools:
#    - name: install helpful developer tools
#      apt:
#        name: vim
#        state: latest